### ISSUE TITLE
DnD start behaves correctly in Chrome but not in Firefox

### ISSUE THREAD

**Issue by NOA-Alex** [mendixlabs/app-services-components#11]
I downloaded the example project and started it in Studio Pro 9.18.0 and 9.6.0 (as the example is created in 9.6.0). Without changing anything on the project.
In Firefox (latest release, 105) when I start dragging, the block icon appears and is not moving the rest of the list when I move the dragged item around. I need to release the mouse button to see the other list items move out of the way. And then I need to click another time to drop the item.
I tested the same in Chrome (latest release, 106) and here it behaves correctly (and I can keep the mouse button pressed till I drop the item).

**Comment by ahwelgemoed** [comment]
Thanks for the issue, I can confirm this behavior, Ill find a fix later this week.

**Comment by NOA-Alex** [comment]
You are welcome. I will use for now Chrome for development and testing. But I can't force all end-user to use only Chrome. So having at least Chrome and Firefox working behaving correctly would be quite important.
Otherwise a splendid plugin!
Though I am trying to make it work also for offline web app. The only thing which is not working for that out of the box is the JSON parsing/mapping in a Nanoflow. As for offline apps Microflows are not allowed. In case you have also or plan anything in that direction please let me know.

**Comment by ahwelgemoed** [comment]
I've pushed a fix to the marketplace `3.0.3` for firefox. Let me know if there is still an issue.

I have no plans to add `JSON parsing/mapping in a Nanoflow.` but a Nanoflows is just Javascript, it should not be too hard to read and parse the json with `JSON.parse()`.

**Comment by NOA-Alex** [comment]
Thanks for the new update. Just tested it in Chrome and Firefox and it works like a charm.
As for the Nanoflow version of it I got that already running. Fortunately your Microflow is straight forward.
Thanks a lot.
