### ISSUE TITLE
Change "Month offset" property of Native Calendar programmatically.

### ISSUE THREAD

**Issue by JosiasFeulner** [mendixlabs/app-services-components#3]
**Is your feature request related to a problem? Please describe.**
I am using the Native Calendar widget. And i need to set the "Month offset" property of the widget programmatically.

**Describe the solution you'd like**
An option to set the month offset property with a date and time attribute of an entity.

**Additional context**
When the user selects a date and the page with the calendar opens, i want the month that is shown to be the same one the user selected.

**Comment by ahwelgemoed** [comment]
Hey- Happy to help but can find a "Month offset" property do you mean the "Months from now" property? 

So you want to pass a Date time to the widget and that must be the "Start" date? or am I mis understanding the feature?

**Comment by JosiasFeulner** [comment]
> Happy to help but can find a "Month offset" property do you mean the "Months from now" property? <

Yes, this is the property i want to change;

![monthOffset](https://user-images.githubusercontent.com/87764019/128520219-4cfa1758-3cfe-4f53-b7ae-31b34e6bd5ad.PNG)

> So you want to pass a Date time to the widget and that must be the "Start" date? or am I mis understanding the feature? <

That is exactly what i want. Thank you for the fast reply.

**Comment by ahwelgemoed** [comment]
Great - Ill have a look on Monday, what I can do here and report back.

**Comment by ahwelgemoed** [comment]
Dag @JosiasFeulner -

I have updated the widget to allow Dynamic Set Month Offset - Please update to `v1.0.4` 
<img width="788" alt="Screenshot 2021-08-09 at 11 29 26" src="https://user-images.githubusercontent.com/29273599/128686539-9cb9c486-3233-44b8-a5ef-434a5321fa3d.png">

**Comment by ahwelgemoed** [comment]
Let me know if all is good and Ill close the issue

**Comment by JosiasFeulner** [comment]
It works exactly as requested. Thank you for the quick work
