### ISSUE TITLE
Event onMonthChange

### ISSUE THREAD

**Issue by AlexEspert** [mendixlabs/app-services-components#5]
Hello there,

I am already using the event of clicking on a day to show some info to the user under the calendar, but I would like to know: How can I trigger an event when the user changes the visible month? I mean, how can i know when the user presses the left/right arrows?

Thank you in advance
Alejandro Espert
![Snap](https://user-images.githubusercontent.com/102971523/161554148-7db6f8e0-042a-4c8e-b8db-59f02e98bc1e.PNG)

**Comment by ahwelgemoed** [comment]
Hey Alejandro
Currently there is no way to do that. It is something I could add in, but I can't think of use case? Could you maybe explain why you want it, or how you would like to work. Im happy to add it but dont want to bloat the Widget unnecessary.

Off the top of my head, I can trigger an action, micro/nano flow, on button press.
Regards, Arno

**Comment by AlexEspert** [comment]
Hello Arno,

Thanks for answering so fast.

When a user presses an event of a day, I am showing under the calendar the details of that event pressed.
I would like that, when the user presses the arrows to change the month, I could empty those details. As you already said, with that possibility, I could create a customized nanoflow to do that, and in the future I'm sure I would use it for other things too

Thank you,
Alejandro Espert.

**Comment by ahwelgemoed** [comment]
great, Ill look into it at some point this week and let you know, thanks for the suggestion.

**Comment by ahwelgemoed** [comment]
Hey Hey , I have put it on my schedule, but I don't have a lot of time for it, right now. 
I will get to it in the next 2 weeks.
Sorry about that

**Comment by ahwelgemoed** [comment]
Hey @AlexEspert .
Could you test [this](https://github.com/mendixlabs/app-services-components/files/8608997/1.0.7.zip) Widget and let me know if this is what you are looking for?
Ive made it call an action on arrow click, left or right, but I did not pass it a param to the function.

**Comment by AlexEspert** [comment]
> Hey @AlexEspert . Could you test [this](https://github.com/mendixlabs/app-services-components/files/8608997/1.0.7.zip) Widget and let me know if this is what you are looking for? Ive made it call an action on arrow click, left or right, but I did not pass it a param to the function.


Hello Arno,

First of all, SORRY SO MUCH for taking so long to reply.
The changes you made on the widget are exactly what we needed and work PERFECT.

Thank you very much!!!

Could you put it on the marketplace (in order to avoid possible new branches/conflicts with future updates)?

Best regards.
Alex
