### ISSUE TITLE
"screen-shot-mx" erro in using dynamics images

### ISSUE THREAD

**Issue by marceloPenninck** [mendixlabs/app-services-components#6]
**Package/screen-shot-mx/**

**I am trying to get two images from different entities, but when generating the PDF, always brings me the first image only.. **

**Comment by ahwelgemoed** [comment]
Hey - Could you maybe show a screenshot of your implementation, and explain a bit more about what you are trying to do?

As the Screenshot Widget does what it says on the tin. It can only print out what is in the DOM/browser at that point.

Thanks 👋🏽

**Comment by marceloPenninck** [comment]
Hi 

This is my first entity
![image](https://user-images.githubusercontent.com/49404406/163587255-5a8f9c78-56c8-45c9-a01e-aa0bb6cbc14c.png)

This is my second entity with the image.
![Uploading image.png…]()

The DOM/Browser is showing the right images, but when I click on the button to generate the PDF, the second image always brings the first image.

The is another error that I found as well. if I change the image on the DOM/Browser shows the right one, but on the PDF still the old one.

**Comment by marceloPenninck** [comment]
First image PDF
![image](https://user-images.githubusercontent.com/49404406/163589377-52cc44d5-0bcd-4913-aee5-73094e513246.png)

Second Image PDF
![image](https://user-images.githubusercontent.com/49404406/163589972-6f6efcb9-3f5a-48c1-8d4f-5ef1d0210d47.png)


First Image Browser
![image](https://user-images.githubusercontent.com/49404406/163589545-2612046e-0d65-4e07-817e-97bc4c2905fc.png)

Second Image Browser
![image](https://user-images.githubusercontent.com/49404406/163590019-610ecd3a-0945-4475-bf55-12091e033732.png)

**Comment by marceloPenninck** [comment]
Hi, has the information that I sent helped? I still facing the same problem. I do not know how to solve it.

**Comment by ahwelgemoed** [comment]
Hey Hey , I have put it on my schedule, but I don't have a lot of time for it, right now. 
I will get to it in the next 2 weeks.
Sorry about that

**Comment by ahwelgemoed** [comment]
Hey @marceloPenninck 
I was able to replicate the issue. 

There seems to be a problem in the underlying package we use, in combination with browser security.

So for now there is no way to really solve it. I will add this as a known issue.

Thank you

**Comment by marceloPenninck** [comment]
Thanks, I will try to do another thing so.
